name: Continuous Deployment

on:
    push:
        branches:
            - 'main'
            - 'develop' 

concurrency:
    group: ${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true
    
jobs:

    publish:
        uses: srinivas-kujala/.github/workflows/publish-docker-image.yml@main
        with:
            branch-name: ${{ github.ref_name }}
            image-name: ${{ VARS.IMAGE_NAME }}
            image-path: ${{ VARS.IMAGE_PATH }}
            project-path:  ${{ vars.PROJECT_PATH }}
            nuget-path:  'src\NuGet.config'
        secrets:
            jfrog-password: ${{ secrets.JFROG_PASSWORD }}
            acr-password: ${{ secrets.ACR_PASSWORD }}

    update-helm:
        needs: publish
        uses: srinivas-kujala/.github/workflows/update-helm-charts.yml@main
        with:
            environment: ${{ VARS.ENVIRONMENT }}
            tag-value: ${{ needs.publish.outputs.version }}
            application-value-path: 'application\values_${{ github.ref_name }}.yaml'